### ISSUE TITLE
The quality of the code is horrendous

### ISSUE THREAD

**Issue by Uniminin** [RealistikOsu/RealistikPanel#54]
Some Reason Includes:
- No CI
- Commit spamming
- ~~No commit organization~~
- ~~pushing directly to master instead of making merge requests and implementing features there~~
- Making the repositories hard to contribute
- No abstracting
- No documentation
- No repository management
- No Gitpod Integration
- No Dockerfile, Makefile
- ~~No Module version specified in `requirements.txt~~

**Comment by Uniminin** [comment]
Important Things to do: (`*` -> done. `x` -> not done yet. `?` not sure.)
* Peer Review before merging Pull Requests [?]
* Add CL [x]
* Proper Abstraction [x]
* Document the project [x]
* Integrate Gitpod [x]
* Add Dockerfile [x]
* Add Makefile [x]
* Specify All Python Module versions [*]

**Comment by barrack-obama** [comment]
"You may notice that some of this code (especially the early one) is not too great. This is because this is a learning trip for me. I am using a lot of libraries and concepts that are new to me and it's the first time I'm doing them. This may be reflected in the quality of the code. I will try to fix up or replace some of the old code when I'm satisfied with the feature set."
